### ISSUE TITLE
Your installed version of RT (4.4.1) is too new

### ISSUE THREAD

**Issue by tbrumm** [cloos/RT-Extension-AddAttachmentsFromTransactions#2]
Moin Chris,
hope your doing well. Just tried to install your Extension to latest RT (4.4.1) and got this:

Using RT configuration from /opt/rt4/lib/RT.pm:
html       => /opt/rt4/local/plugins/RT-Extension-AddAttachmentsFromTransactions/html
lib        => /opt/rt4/local/plugins/RT-Extension-AddAttachmentsFromTransactions/lib

**** Error: Your installed version of RT (4.4.1) is too new; this extension
            only works with versions older than 4.4.0.

**Comment by netsandbox** [comment]
The functionality of this extension is included in RT 4.4.0 ;-)
The code in this extension was always from a BPS feature branch that was finally merged in RT 4.4.0.
