### ISSUE TITLE
Conflict with RT::Extension::Announce

### ISSUE THREAD

**Issue by tbrumm** [cloos/RT-Extension-AddAttachmentsFromTransactions#3]
Hi Chris,
i have a conflict with Announce Addon from RT and yours:

Subroutine AddAttachmentsFromHeaders redefined at /opt/rt4/local/plugins/RT-Extension-AddAttachmentsFromTransactions/lib/RT/Extension/AddAttachmentsFromTransactions.pm line 49, <STDIN> line 1. (/opt/rt4/local/plugins/RT-Extension-AddAttachmentsFromTransactions/lib/RT/Extension/AddAttachmentsFromTransactions.pm:49)****

Torsten

**Comment by netsandbox** [comment]
Hi Torsten,
just installed the two plugins on RT 4.2.14 and don't see any problems or error messages.

Chris
